name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-lib-project:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install modules
      run: yarn

    - name: Check
      run: yarn validate

    - name: Build typescript & flow
      run: yarn build